# Generated by Django 4.1.4 on 2022-12-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSequence',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('protein_id', models.CharField(max_length=15)),
                ('protein_sequence', models.CharField(max_length=40000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSequenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='datasequence_files')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('protein_id', models.CharField(max_length=15)),
                ('organism_taxa_id', models.CharField(max_length=20)),
                ('organism_clade_idenitifer', models.CharField(max_length=5)),
                ('organism_scientific_name', models.CharField(max_length=50)),
                ('domain_description', models.TextField()),
                ('domain_id', models.CharField(max_length=70)),
                ('domain_start_coordinate', models.CharField(max_length=10)),
                ('domain_end_coordinate', models.CharField(max_length=10)),
                ('length_of_protein', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dataset_files')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
